export const calendarEvents = [
    {
        id: 1,
        title: "Capacitación de seguridad",
        date: "2026-09-08",
        time: "10:00",
        endTime: "12:00",
        category: "capacitacion",
        location: "Auditorio principal",
        visibility: "empresa",
        audience: "Todos los empleados",
        description:
            "Capacitación anual sobre seguridad y procedimientos internos.",
    },
    {
        id: 2,
        title: "Reunión de Tecnología",
        date: "2026-09-10",
        time: "09:00",
        endTime: "10:00",
        category: "reunion",
        location: "Sala de reuniones 2",
        visibility: "departamento",
        audience: "Departamento de Tecnología",
        description:
            "Reunión mensual de coordinación del departamento.",
    },
    {
        id: 3,
        title: "Evento institucional",
        date: "2026-09-18",
        time: "15:00",
        endTime: "18:00",
        category: "actividad",
        location: "Patio central",
        visibility: "empresa",
        audience: "Todos los empleados",
        description:
            "Actividad institucional de integración del personal.",
    },
    {
        id: 4,
        title: "Reunión de sucursal",
        date: "2026-09-24",
        time: "11:00",
        endTime: "12:00",
        category: "sucursal",
        location: "Sala de reuniones",
        visibility: "sucursal",
        audience: "Sucursal Central",
        description:
            "Reunión de coordinación de la sucursal.",
    },
    {
        id: 5,
        title: "Feriado nacional",
        date: "2026-09-21",
        time: null,
        endTime: null,
        category: "feriado",
        location: null,
        visibility: "empresa",
        audience: "Todos los empleados",
        description:
            "Feriado nacional.",
    },
    {
        id: 6,
        title: "Reunión general",
        date: "2026-09-29",
        time: "14:00",
        endTime: "15:30",
        category: "reunion",
        location: "Auditorio principal",
        visibility: "empresa",
        audience: "Todos los empleados",
        description:
            "Reunión general para revisar las actividades del trimestre.",
    },
    {
        id: 7,
        title: "Fecha importante",
        date: "2026-09-30",
        time: null,
        endTime: null,
        category: "empresa",
        location: null,
        visibility: "empresa",
        audience: "Todos los empleados",
        description:
            "Fecha importante dentro del calendario corporativo.",
    },
];